name: .NET CI with SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, Test and Analyze
    runs-on: windows-latest

    steps:
      # Setup JDK (Sonar a besoin de Java)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      # Récupérer le code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Installer .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Cache Sonar
      - name: Cache Sonar packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Sonar scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      # Installer Sonar scanner si pas en cache
      - name: Install Sonar scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path ${{ runner.temp }}\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path ${{ runner.temp }}\scanner

      # Analyse Sonar + Build + Tests
      - name: Build and Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
            cd backend
            # Begin Sonar
            ${{ runner.temp }}\scanner\dotnet-sonarscanner begin /k:"AllanM-dev_portfolio" /o:"allanm-dev" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.coverage.exclusions="**/Migrations/*.cs,**/Program.cs" /d:"sonar.verbose=true" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
            # Build
            dotnet build Portfolio.API\Portfolio.API\Portfolio.API.csproj --configuration Release
            # Test + Coverage
            dotnet test Portfolio.API\Portfolio.Test\Portfolio.Test.csproj --configuration Release --collect:"XPlat Code Coverage;Format=opencover" --settings coverlet.runsettings
            # End Sonar
            ${{ runner.temp }}\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
